// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/kvpb/kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK         Status = 0
	Status_NOT_LEADER Status = 1
	Status_TIMEOUT    Status = 2
	Status_ERROR      Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "NOT_LEADER",
		2: "TIMEOUT",
		3: "ERROR",
	}
	Status_value = map[string]int32{
		"OK":         0,
		"NOT_LEADER": 1,
		"TIMEOUT":    2,
		"ERROR":      3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kvpb_kv_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_kvpb_kv_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{0}
}

type Op int32

const (
	Op_PUT    Op = 0
	Op_DELETE Op = 1
	Op_CAS    Op = 2
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
		2: "CAS",
	}
	Op_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
		"CAS":    2,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kvpb_kv_proto_enumTypes[1].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_proto_kvpb_kv_proto_enumTypes[1]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{1}
}

// Command is the payload of a replicated log entry.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=raftkv.kv.Op" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Expected      []byte                 `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	ExpectAbsent  bool                   `protobuf:"varint,5,opt,name=expect_absent,json=expectAbsent,proto3" json:"expect_absent,omitempty"`
	ClientId      uint64                 `protobuf:"varint,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_PUT
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Command) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *Command) GetExpectAbsent() bool {
	if x != nil {
		return x.ExpectAbsent
	}
	return false
}

func (x *Command) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Command) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      uint64                 `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.kv.Status" json:"status,omitempty"`
	LeaderHint    uint64                 `protobuf:"varint,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *PutResponse) GetLeaderHint() uint64 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

func (x *PutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.kv.Status" json:"status,omitempty"`
	LeaderHint    uint64                 `protobuf:"varint,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Found         bool                   `protobuf:"varint,4,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *GetResponse) GetLeaderHint() uint64 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *DeleteRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.kv.Status" json:"status,omitempty"`
	LeaderHint    uint64                 `protobuf:"varint,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Existed       bool                   `protobuf:"varint,4,opt,name=existed,proto3" json:"existed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *DeleteResponse) GetLeaderHint() uint64 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

type CASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expected      []byte                 `protobuf:"bytes,2,opt,name=expected,proto3" json:"expected,omitempty"`
	ExpectAbsent  bool                   `protobuf:"varint,3,opt,name=expect_absent,json=expectAbsent,proto3" json:"expect_absent,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      uint64                 `protobuf:"varint,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASRequest) Reset() {
	*x = CASRequest{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASRequest) ProtoMessage() {}

func (x *CASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASRequest.ProtoReflect.Descriptor instead.
func (*CASRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{7}
}

func (x *CASRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CASRequest) GetExpected() []byte {
	if x != nil {
		return x.Expected
	}
	return nil
}

func (x *CASRequest) GetExpectAbsent() bool {
	if x != nil {
		return x.ExpectAbsent
	}
	return false
}

func (x *CASRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CASRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CASRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type CASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=raftkv.kv.Status" json:"status,omitempty"`
	LeaderHint    uint64                 `protobuf:"varint,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Swapped       bool                   `protobuf:"varint,4,opt,name=swapped,proto3" json:"swapped,omitempty"`
	Found         bool                   `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	Current       []byte                 `protobuf:"bytes,6,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASResponse) Reset() {
	*x = CASResponse{}
	mi := &file_proto_kvpb_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASResponse) ProtoMessage() {}

func (x *CASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvpb_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASResponse.ProtoReflect.Descriptor instead.
func (*CASResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvpb_kv_proto_rawDescGZIP(), []int{8}
}

func (x *CASResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *CASResponse) GetLeaderHint() uint64 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

func (x *CASResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CASResponse) GetSwapped() bool {
	if x != nil {
		return x.Swapped
	}
	return false
}

func (x *CASResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CASResponse) GetCurrent() []byte {
	if x != nil {
		return x.Current
	}
	return nil
}

var File_proto_kvpb_kv_proto protoreflect.FileDescriptor

const file_proto_kvpb_kv_proto_rawDesc = "" +
	"\n" +
	"\x13proto/kvpb/kv.proto\x12\traftkv.kv\"\xc0\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\x02op\x18\x01 \x01(\x0e2\r.raftkv.kv.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1a\n" +
	"\bexpected\x18\x04 \x01(\fR\bexpected\x12#\n" +
	"\rexpect_absent\x18\x05 \x01(\bR\fexpectAbsent\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\a \x01(\x04R\x03seq\"c\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\"o\n" +
	"\vPutResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.raftkv.kv.StatusR\x06status\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\x04R\n" +
	"leaderHint\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x9b\x01\n" +
	"\vGetResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.raftkv.kv.StatusR\x06status\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\x04R\n" +
	"leaderHint\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x14\n" +
	"\x05found\x18\x04 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"P\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"\x8c\x01\n" +
	"\x0eDeleteResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.raftkv.kv.StatusR\x06status\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\x04R\n" +
	"leaderHint\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\aexisted\x18\x04 \x01(\bR\aexisted\"\xa4\x01\n" +
	"\n" +
	"CASRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bexpected\x18\x02 \x01(\fR\bexpected\x12#\n" +
	"\rexpect_absent\x18\x03 \x01(\bR\fexpectAbsent\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\"\xb9\x01\n" +
	"\vCASResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.raftkv.kv.StatusR\x06status\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\x04R\n" +
	"leaderHint\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\aswapped\x18\x04 \x01(\bR\aswapped\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\fR\acurrent*8\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\x01\x12\v\n" +
	"\aTIMEOUT\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*\"\n" +
	"\x02Op\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\a\n" +
	"\x03CAS\x10\x022\xe5\x01\n" +
	"\x02KV\x124\n" +
	"\x03Put\x12\x15.raftkv.kv.PutRequest\x1a\x16.raftkv.kv.PutResponse\x124\n" +
	"\x03Get\x12\x15.raftkv.kv.GetRequest\x1a\x16.raftkv.kv.GetResponse\x12=\n" +
	"\x06Delete\x12\x18.raftkv.kv.DeleteRequest\x1a\x19.raftkv.kv.DeleteResponse\x124\n" +
	"\x03CAS\x12\x15.raftkv.kv.CASRequest\x1a\x16.raftkv.kv.CASResponseB'Z%github.com/Jenil133/raftkv/proto/kvpbb\x06proto3"

var (
	file_proto_kvpb_kv_proto_rawDescOnce sync.Once
	file_proto_kvpb_kv_proto_rawDescData []byte
)

func file_proto_kvpb_kv_proto_rawDescGZIP() []byte {
	file_proto_kvpb_kv_proto_rawDescOnce.Do(func() {
		file_proto_kvpb_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kvpb_kv_proto_rawDesc), len(file_proto_kvpb_kv_proto_rawDesc)))
	})
	return file_proto_kvpb_kv_proto_rawDescData
}

var file_proto_kvpb_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_kvpb_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_kvpb_kv_proto_goTypes = []any{
	(Status)(0),            // 0: raftkv.kv.Status
	(Op)(0),                // 1: raftkv.kv.Op
	(*Command)(nil),        // 2: raftkv.kv.Command
	(*PutRequest)(nil),     // 3: raftkv.kv.PutRequest
	(*PutResponse)(nil),    // 4: raftkv.kv.PutResponse
	(*GetRequest)(nil),     // 5: raftkv.kv.GetRequest
	(*GetResponse)(nil),    // 6: raftkv.kv.GetResponse
	(*DeleteRequest)(nil),  // 7: raftkv.kv.DeleteRequest
	(*DeleteResponse)(nil), // 8: raftkv.kv.DeleteResponse
	(*CASRequest)(nil),     // 9: raftkv.kv.CASRequest
	(*CASResponse)(nil),    // 10: raftkv.kv.CASResponse
}
var file_proto_kvpb_kv_proto_depIdxs = []int32{
	1,  // 0: raftkv.kv.Command.op:type_name -> raftkv.kv.Op
	0,  // 1: raftkv.kv.PutResponse.status:type_name -> raftkv.kv.Status
	0,  // 2: raftkv.kv.GetResponse.status:type_name -> raftkv.kv.Status
	0,  // 3: raftkv.kv.DeleteResponse.status:type_name -> raftkv.kv.Status
	0,  // 4: raftkv.kv.CASResponse.status:type_name -> raftkv.kv.Status
	3,  // 5: raftkv.kv.KV.Put:input_type -> raftkv.kv.PutRequest
	5,  // 6: raftkv.kv.KV.Get:input_type -> raftkv.kv.GetRequest
	7,  // 7: raftkv.kv.KV.Delete:input_type -> raftkv.kv.DeleteRequest
	9,  // 8: raftkv.kv.KV.CAS:input_type -> raftkv.kv.CASRequest
	4,  // 9: raftkv.kv.KV.Put:output_type -> raftkv.kv.PutResponse
	6,  // 10: raftkv.kv.KV.Get:output_type -> raftkv.kv.GetResponse
	8,  // 11: raftkv.kv.KV.Delete:output_type -> raftkv.kv.DeleteResponse
	10, // 12: raftkv.kv.KV.CAS:output_type -> raftkv.kv.CASResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_kvpb_kv_proto_init() }
func file_proto_kvpb_kv_proto_init() {
	if File_proto_kvpb_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kvpb_kv_proto_rawDesc), len(file_proto_kvpb_kv_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kvpb_kv_proto_goTypes,
		DependencyIndexes: file_proto_kvpb_kv_proto_depIdxs,
		EnumInfos:         file_proto_kvpb_kv_proto_enumTypes,
		MessageInfos:      file_proto_kvpb_kv_proto_msgTypes,
	}.Build()
	File_proto_kvpb_kv_proto = out.File
	file_proto_kvpb_kv_proto_goTypes = nil
	file_proto_kvpb_kv_proto_depIdxs = nil
}
