// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/docpb/doc.proto

package docpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK               Code = 0
	Code_NOT_FOUND        Code = 1
	Code_VERSION_CONFLICT Code = 2
	Code_INVALID          Code = 3
	Code_UNAVAILABLE      Code = 4
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "OK",
		1: "NOT_FOUND",
		2: "VERSION_CONFLICT",
		3: "INVALID",
		4: "UNAVAILABLE",
	}
	Code_value = map[string]int32{
		"OK":               0,
		"NOT_FOUND":        1,
		"VERSION_CONFLICT": 2,
		"INVALID":          3,
		"UNAVAILABLE":      4,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_docpb_doc_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_proto_docpb_doc_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{0}
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Json          []byte                 `protobuf:"bytes,4,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_docpb_doc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Document) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Json          []byte                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`
	HasIfVersion  bool                   `protobuf:"varint,4,opt,name=has_if_version,json=hasIfVersion,proto3" json:"has_if_version,omitempty"`
	IfVersion     uint64                 `protobuf:"varint,5,opt,name=if_version,json=ifVersion,proto3" json:"if_version,omitempty"` // 0 with has_if_version means "create only"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_docpb_doc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *PutRequest) GetHasIfVersion() bool {
	if x != nil {
		return x.HasIfVersion
	}
	return false
}

func (x *PutRequest) GetIfVersion() uint64 {
	if x != nil {
		return x.IfVersion
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_docpb_doc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	HasIfVersion  bool                   `protobuf:"varint,3,opt,name=has_if_version,json=hasIfVersion,proto3" json:"has_if_version,omitempty"`
	IfVersion     uint64                 `protobuf:"varint,4,opt,name=if_version,json=ifVersion,proto3" json:"if_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_docpb_doc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetHasIfVersion() bool {
	if x != nil {
		return x.HasIfVersion
	}
	return false
}

func (x *DeleteRequest) GetIfVersion() uint64 {
	if x != nil {
		return x.IfVersion
	}
	return 0
}

// PatchRequest carries an RFC 7386 JSON merge patch.
type PatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Patch         []byte                 `protobuf:"bytes,3,opt,name=patch,proto3" json:"patch,omitempty"`
	HasIfVersion  bool                   `protobuf:"varint,4,opt,name=has_if_version,json=hasIfVersion,proto3" json:"has_if_version,omitempty"`
	IfVersion     uint64                 `protobuf:"varint,5,opt,name=if_version,json=ifVersion,proto3" json:"if_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRequest) Reset() {
	*x = PatchRequest{}
	mi := &file_proto_docpb_doc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRequest) ProtoMessage() {}

func (x *PatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRequest.ProtoReflect.Descriptor instead.
func (*PatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{4}
}

func (x *PatchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *PatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchRequest) GetPatch() []byte {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *PatchRequest) GetHasIfVersion() bool {
	if x != nil {
		return x.HasIfVersion
	}
	return false
}

func (x *PatchRequest) GetIfVersion() uint64 {
	if x != nil {
		return x.IfVersion
	}
	return 0
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	AfterId       string                 `protobuf:"bytes,2,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"` // exclusive
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_docpb_doc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{5}
}

func (x *ScanRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ScanRequest) GetAfterId() string {
	if x != nil {
		return x.AfterId
	}
	return ""
}

func (x *ScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=raftkv.doc.Code" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Doc           *Document              `protobuf:"bytes,3,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_docpb_doc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetDoc() *Document {
	if x != nil {
		return x.Doc
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=raftkv.doc.Code" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Docs          []*Document            `protobuf:"bytes,3,rep,name=docs,proto3" json:"docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_docpb_doc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_docpb_doc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_docpb_doc_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *ScanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScanResponse) GetDocs() []*Document {
	if x != nil {
		return x.Docs
	}
	return nil
}

var File_proto_docpb_doc_proto protoreflect.FileDescriptor

const file_proto_docpb_doc_proto_rawDesc = "" +
	"\n" +
	"\x15proto/docpb/doc.proto\x12\n" +
	"raftkv.doc\"h\n" +
	"\bDocument\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x12\n" +
	"\x04json\x18\x04 \x01(\fR\x04json\"\x95\x01\n" +
	"\n" +
	"PutRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04json\x18\x03 \x01(\fR\x04json\x12$\n" +
	"\x0ehas_if_version\x18\x04 \x01(\bR\fhasIfVersion\x12\x1d\n" +
	"\n" +
	"if_version\x18\x05 \x01(\x04R\tifVersion\"<\n" +
	"\n" +
	"GetRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x84\x01\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12$\n" +
	"\x0ehas_if_version\x18\x03 \x01(\bR\fhasIfVersion\x12\x1d\n" +
	"\n" +
	"if_version\x18\x04 \x01(\x04R\tifVersion\"\x99\x01\n" +
	"\fPatchRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\fR\x05patch\x12$\n" +
	"\x0ehas_if_version\x18\x04 \x01(\bR\fhasIfVersion\x12\x1d\n" +
	"\n" +
	"if_version\x18\x05 \x01(\x04R\tifVersion\"^\n" +
	"\vScanRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x19\n" +
	"\bafter_id\x18\x02 \x01(\tR\aafterId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"n\n" +
	"\bResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.raftkv.doc.CodeR\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12&\n" +
	"\x03doc\x18\x03 \x01(\v2\x14.raftkv.doc.DocumentR\x03doc\"t\n" +
	"\fScanResponse\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.raftkv.doc.CodeR\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12(\n" +
	"\x04docs\x18\x03 \x03(\v2\x14.raftkv.doc.DocumentR\x04docs*Q\n" +
	"\x04Code\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x14\n" +
	"\x10VERSION_CONFLICT\x10\x02\x12\v\n" +
	"\aINVALID\x10\x03\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x042\x9f\x02\n" +
	"\x04Docs\x123\n" +
	"\x03Put\x12\x16.raftkv.doc.PutRequest\x1a\x14.raftkv.doc.Response\x123\n" +
	"\x03Get\x12\x16.raftkv.doc.GetRequest\x1a\x14.raftkv.doc.Response\x129\n" +
	"\x06Delete\x12\x19.raftkv.doc.DeleteRequest\x1a\x14.raftkv.doc.Response\x127\n" +
	"\x05Patch\x12\x18.raftkv.doc.PatchRequest\x1a\x14.raftkv.doc.Response\x129\n" +
	"\x04Scan\x12\x17.raftkv.doc.ScanRequest\x1a\x18.raftkv.doc.ScanResponseB(Z&github.com/Jenil133/raftkv/proto/docpbb\x06proto3"

var (
	file_proto_docpb_doc_proto_rawDescOnce sync.Once
	file_proto_docpb_doc_proto_rawDescData []byte
)

func file_proto_docpb_doc_proto_rawDescGZIP() []byte {
	file_proto_docpb_doc_proto_rawDescOnce.Do(func() {
		file_proto_docpb_doc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_docpb_doc_proto_rawDesc), len(file_proto_docpb_doc_proto_rawDesc)))
	})
	return file_proto_docpb_doc_proto_rawDescData
}

var file_proto_docpb_doc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_docpb_doc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_docpb_doc_proto_goTypes = []any{
	(Code)(0),             // 0: raftkv.doc.Code
	(*Document)(nil),      // 1: raftkv.doc.Document
	(*PutRequest)(nil),    // 2: raftkv.doc.PutRequest
	(*GetRequest)(nil),    // 3: raftkv.doc.GetRequest
	(*DeleteRequest)(nil), // 4: raftkv.doc.DeleteRequest
	(*PatchRequest)(nil),  // 5: raftkv.doc.PatchRequest
	(*ScanRequest)(nil),   // 6: raftkv.doc.ScanRequest
	(*Response)(nil),      // 7: raftkv.doc.Response
	(*ScanResponse)(nil),  // 8: raftkv.doc.ScanResponse
}
var file_proto_docpb_doc_proto_depIdxs = []int32{
	0, // 0: raftkv.doc.Response.code:type_name -> raftkv.doc.Code
	1, // 1: raftkv.doc.Response.doc:type_name -> raftkv.doc.Document
	0, // 2: raftkv.doc.ScanResponse.code:type_name -> raftkv.doc.Code
	1, // 3: raftkv.doc.ScanResponse.docs:type_name -> raftkv.doc.Document
	2, // 4: raftkv.doc.Docs.Put:input_type -> raftkv.doc.PutRequest
	3, // 5: raftkv.doc.Docs.Get:input_type -> raftkv.doc.GetRequest
	4, // 6: raftkv.doc.Docs.Delete:input_type -> raftkv.doc.DeleteRequest
	5, // 7: raftkv.doc.Docs.Patch:input_type -> raftkv.doc.PatchRequest
	6, // 8: raftkv.doc.Docs.Scan:input_type -> raftkv.doc.ScanRequest
	7, // 9: raftkv.doc.Docs.Put:output_type -> raftkv.doc.Response
	7, // 10: raftkv.doc.Docs.Get:output_type -> raftkv.doc.Response
	7, // 11: raftkv.doc.Docs.Delete:output_type -> raftkv.doc.Response
	7, // 12: raftkv.doc.Docs.Patch:output_type -> raftkv.doc.Response
	8, // 13: raftkv.doc.Docs.Scan:output_type -> raftkv.doc.ScanResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_docpb_doc_proto_init() }
func file_proto_docpb_doc_proto_init() {
	if File_proto_docpb_doc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_docpb_doc_proto_rawDesc), len(file_proto_docpb_doc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_docpb_doc_proto_goTypes,
		DependencyIndexes: file_proto_docpb_doc_proto_depIdxs,
		EnumInfos:         file_proto_docpb_doc_proto_enumTypes,
		MessageInfos:      file_proto_docpb_doc_proto_msgTypes,
	}.Build()
	File_proto_docpb_doc_proto = out.File
	file_proto_docpb_doc_proto_goTypes = nil
	file_proto_docpb_doc_proto_depIdxs = nil
}
